name: Deploy Admin Web Application

on:
  push:
    branches:
      - main
    paths:
      - 'apps/admin-web/**'
      - '.github/workflows/deploy-admin-web.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy_admin_web:
    name: Deploy Admin Web to Azure Static Web Apps
    runs-on: ubuntu-latest

    env:
      VITE_AZURE_AD_CLIENT_ID: ${{ secrets.VITE_AZURE_AD_CLIENT_ID }}
      VITE_AZURE_AD_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      VITE_AZURE_AD_REDIRECT_URI: ${{ secrets.VITE_AZURE_AD_REDIRECT_URI }}
      VITE_AZURE_AD_POST_LOGOUT_REDIRECT_URI: ${{ secrets.VITE_AZURE_AD_POST_LOGOUT_REDIRECT_URI }}
      VITE_AZURE_AD_API_CLIENT_ID: ${{ secrets.VITE_AZURE_AD_API_CLIENT_ID }}
      VITE_AZURE_AD_API_SCOPE_URI: ${{ secrets.VITE_AZURE_AD_API_SCOPE_URI }}
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      AZURE_CLIENT_ID: ${{ secrets.VITE_AZURE_AD_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm

      - name: Install dependencies and build application
        working-directory: apps/admin-web
        run: |
          npm ci
          npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_APP_DEPLOY_KEY }}
          repo_token: ${{ secrets.PERSONAL_TOKEN }}
          action: upload
          app_location: apps/admin-web
          api_location: ''
          app_artifact_location: dist
